numero1 = input("Escolha um número")
numero2 = input("Escolha outro número para fazer a soma")
numero1 = float(numero1)
numero2 = float(numero2)
print("O resultado de", numero1, "+", numero2, "é", numero1 + numero2)
